version: 2
updates:
  # Check for updates in the GitHub Actions workflow files
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cron: "0 */6 * * *"
  # Check for updates for NDK dependencies
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "cron"
      cron: "0 */6 * * *"

